"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Constraints:

    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.

"""


class Solution:

    def findTheDifference(self, s, t):
        letter_count = {}

        # Count each letter in t
        for letter in t:
            letter_count[letter] = letter_count.get(letter, 0) + 1

        # Subtract the counts based on string s
        for letter in s:
            letter_count[letter] -= 1

        # The remaining letter with count 1 is the extra letter
        for letter, count in letter_count.items():
            if count == 1:
                return letter


if __name__ == '__main__':
    s = "abcd"
    t = "abcde"

    # s = "a"
    # t = "aa"

    sol = Solution()
    ans = sol.findTheDifference(s, t)
    print(ans)

